const message = Object.freeze({
  fields_cannot_blank: 'trans.fields_cannot_blank',
  fields_invalid: 'trans.fields_invalid',
  server_error: 'trans.server_error',
  duplicate_login: 'trans.duplicate_login',
  update_failed: 'trans.update_failed',
  access_token_invalid: 'trans.access_token_invalid',
  please_check_otp_sms: 'trans.please_check_otp_sms',
  account_locked: 'trans.account_locked',
  please_check_mail_confirm: 'trans.please_check_mail_confirm',
  wrong_email_or_pass: 'trans.wrong_email_or_pass',
  captcha_is_not_verify: 'trans.captcha_is_not_verify',
  account_is_not_active: 'trans.account_is_not_active',
  phone_number_exist: 'trans.phone_number_exist',
  email_exist: 'trans.email_exist',
  user_name_exist: 'trans.user_name_exist',
  wrong_code: 'trans.wrong_code',
  code_expire: 'trans.code_expire',
  wrong_phone_number: 'trans.wrong_phone_number',
  link_expired: 'trans.link_expired',
  send_mail_error: 'trans.send_mail_error',
  security_pending: 'trans.security_pending',
  security_fail: 'trans.security_fail',
  setting_password_pending: 'trans.setting_password_pending',
  setting_phone_number_2fa_sms: 'trans.setting_phone_number_2fa_sms',
  not_exist_account_sns: 'trans.not_exist_account_sns',
  not_exist_email: 'trans.not_exist_email',
  account_sns_exist: 'trans.account_sns_exist',
  wrong_email_or_phone_number: 'trans.wrong_email_or_phone_number',
  pending_2fa: 'trans.pending_2fa',
  wrong_token_app: 'trans.wrong_token_app',
  setting_password_wrong: 'trans.setting_password_wrong',
  release_2fa_pending: 'trans.release_2fa_pending',
  release_code_email_expire: 'trans.release_code_email_expire',
  release_code_email_wrong: 'trans.release_code_email_wrong',
  phone_number_not_found: 'trans.phone_number_not_found',
  trading_account_not_found: 'trans.trading_account_not_found',
  portfolio_is_maximum: 'trans.portfolio_is_maximum',
  user_not_found: 'User not found',
  token_invalid: 'Access token invalid',
  param_invalid: 'Parameter invalid',
  portfolio_not_found: 'Portfolio not found',
  lack_access_token: 'Lack of access token',
  download_exceeded: 'trans.download_exceeded',
  chars_name_exceed: 'trans.name_exceeds_characters',
  chars_description_exceed: 'trans.description_exceeds_characters',
})

const code = Object.freeze({
  SUCCESS: 200,
  ERROR: 500,
  INVALID: 402,
  VALIDATOR: 422,
  AUTHORIZATION: 401,
  NOT_FOUND: 404,
})

const flag = Object.freeze({
  TRUE: 1,
  FALSE: 0,
})

module.exports={
  code,
  message,
  flag,
}
